# SPDX-FileCopyrightText: 2024 Carlo Castoldi <carlo.castoldi@outlook.com>
#
# SPDX-License-Identifier: CC0-1.0

experiment:
  name: "example"
  output_dir: "data/BraiAn_output"

groups:
  HC: ["287HC", "342HC", "343HC", "346HC", "371HC"]
  CTX: ["329CTX", "331CTX", "355CTX", "400CTX", "401CTX", "402CTX"]
  FC: ["367FC", "368FC", "369FC", "426FC", "427FC", "428FC"]

atlas:
  version: "v3"
  excluded-branches: ["retina", "VS", "grv", "fiber tracts", "CB"]

brains:
  raw-metric: "sum"

qupath:
  files:
    dirs:
      output: "data/QuPath_output"
      results_subdir: "results"
      exclusions_subdir: "regions_to_exclude"
    suffix:
      results: "_regions.txt"
      exclusions: "_regions_to_exclude.txt"
    markers:
      AF568: "cFos"
      AF647: "Arc"
  exclude-parents: true
  min-slices: 0