[experiment]
name = "test"

[experiment.group1]
name = "Control (Females)"
dirs = ["42CF", "44CF", "50CF", "52CF", "58CF", "60CF", "74CF", "76CF"]

[experiment.group2]
name = "Stress (Females)"
dirs = ["46SF", "48SF", "54SF", "56SF", "62SF", "64SF", "78SF", "80SF"]

[experiment.group3]
name = "Control (Males)"
dirs = ["41CM", "43CM", "49CM", "51CM", "81CM", "83CM", "89CM", "91CM"]

[experiment.group4]
name = "Stress (Males)"
dirs = ["45SM", "47SM", "53SM", "55SM", "85SM", "87SM", "93SM", "95SM"]

[atlas]
version = "CCFv3"               # ABBA currently uses CCFv3 from Allen Project
excluded-branches = ["retina", "VS", "grv", "fiber tracts", "CB"]

[brains]
area-column = "Area um^2"       # column in QuPath's result CSVs that specifies the area of the regions in µm²
tracer-column = "Num AF647"     # column in QuPath's result CSVs that specifies the number of detection
marker = "CFos"                 # name of the marker QuPath counted
slices-aggregation-mode = "sum" # available options are: 'sum', 'mean'/'avg', 'std', 'variation'/'cvar'
normalization = "Density"       # call get_normalization_methods() on a AnimalGroup object to know its available normalization methods
                                # by default, options are: 'Density', 'Percentage', 'RelativeDensity'

[connectome]
regions-to-plot = "summary structures"      # look into the script for more options
grouped-regions = ["Isocortex", "MY"]       # the following regions are used instead of the corresponding child regions selected with 'regions-to-plot'
min-area = 0.1                              # threshold below which a region of an animal is excluded
min-animals = 4                             # minimum number of animals to use for the cross-correlation of a region
                                            # 'max' means that ALL the animals must have the region, otherwise the correlation is NaN
only-regions-in-all-compared-groups = false # if true, the cross-correlation is done only between regions present in all groups that are being compared
only-regions-with-sufficient-data = false   # if true, the regions with not enough data to compute the cross-correlation with ALL other regions are removed

[connectome.structural]
log10-cutoff = -4.5             # 10^log10-cutoff is the threshold on normalised connection density used to determine structural links between regions
weighted = true

[connectome.functional]
p-cutoff = 0.01                 # threshold on cross-correlation's p-value used to determine functional links between regions
r-cutoff = 0.87                 # threshold on cross-correlation's Pearson coefficient used to determine functional links between regions
weighted = true
use-negative-links = false

[connectome.pruned]
weighted = true
use-negative-links = false

[comparison]
regions-to-plot = "summary structures"      # look into the script for more options
min-area = 0.1                              # threshold below which a region of an animal is excluded

# comparisons often used for groups analysis
# if more than two groups are available, you can compare more different combinations of groups
# Hence the number <n> in [comparisons.<n>]
[comparison.1]
dir = "CF-SF"                   # name of the folder in which to save results
groups = [1, 2]                 # list of indices <n> used in [experiment.group<n>] to define an experimental group

[comparison.2]
dir = "CM-SM"
groups = [3, 4]

[comparison.3]
dir = "CF-SF-CM-SM"
groups = [1, 2, 3, 4]

[pls]
regions-to-plot = "summary structures"      # look into the script for more options
min-area = 0.1                              # threshold below which a region of an animal is excluded
salience-threshold = 1.5                    # threshold on PLS's salience scores to determine which regions change the most in the comparison
rank = 1
num-bootstrap = 5000
num-permutations = 5000
