[tool.poetry]
name = "braian"
version = "0.1.0"
description = "A python library for whole-brain analysis"
authors = ["Carlo Castoldi <carlo.castoldi@in.cnr.it>"]
license = "MPL 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
python-igraph = "^0.10.4"
numpy = "^1.24.3"
pandas = "^2.0.1"
plotly = "^5.14.1"
scipy = "^1.10.1"
networkx = "^3.1"           # used to plot Allen's onthology
pydot = "^1.4.2"            # used to plot Allen's onthology
kaleido = "0.2.1"           # used to export plotly images. "0.2.1.post1" version can't be installed
beautifulsoup4 = "^4.12.2"  # used to blacklist regions from Allen's onthology that have no annotation
bgheatmap = {git = "ssh://git@github.com/carlocastoldi/bg-heatmaps.git", rev = "hemispheres-slicing"}        # used to visualize brain heatmap for IEGs overlaps

[tool.poetry.group.dev.dependencies]
ipython = "^8.13.2"
ipykernel = "^6.23.0"
nbformat = "^5.8.0"
jupyter-client = "<8"
pyzmq = "<25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
